# Generated by Django 4.2.23 on 2025-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
    ]
