# Generated by Django 4.2.23 on 2025-08-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation_approval_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='required_equipments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
