# Generated by Django 4.2.23 on 2025-08-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operation_latitude_operation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='location',
            field=models.CharField(blank=True, help_text='Site name where operation was performed', max_length=255, null=True),
        ),
    ]
