# Generated by Django 4.2.23 on 2025-08-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
