# Generated by Django 4.2.23 on 2025-08-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_operation_latitude_alter_operation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
